print('simon')
print('Ivo')
print('chidi')
print('grace')
print('glory')
# bugs removed
print("car service automated")
print("hello $user your car need servicing now")
print("referral bonus automated")
print("hello $user get 10% on your next purchase when you refer five customers")
